<body class="min-h-lvh">
<div class="h-32">
    <div class="p-2 m-2 bg-green-600">
        <div x-data="{ isOpen: true }">
            <button x-on:click="isOpen = !isOpen" class="text-yellow-400">Show Title</button>
            <h1 x-show="!isOpen" class="text-2xl font-bold text-white">Hello World</h1>
        </div>
    </div>
</div>

<div x-data="exampleRefs()" class="h-32">
    <button x-on:click="toggleInput">Toggle</button>
    <input type="text" x-show="showInput" x-ref="exampleInput" x-model="exampleInput"/>
</div>
<script>
    function exampleRefs() {
        return {
            showInput: false,
            exampleInput: '',
            toggleInput: function() {
                this.showInput = !this.showInput;
                if(this.showInput) {
                    this.$nextTick(() => {
                        this.$refs.exampleInput.focus();
                    });
                }
            }
        }
    }
</script>

<div x-data="exampleWatch()" x-init="init" class="h-32">
    <button @click="open = ! open">Toggle</button>
    <div x-show="open">Open</div>
    <div x-show="!open">Not open</div>
</div>

<script>
    function exampleWatch() {
        return {
            open: false,
            oldOpen: false,
            init: function() {
                this.$watch('open', (newValue) => {
                    console.log('From ' + this.oldOpen + ' to ' + newValue);
                    this.oldOpen = newValue;
                });
            }
        }
    }
</script>
</body>
