<?php declare(strict_types=1);

use Yireo\ExampleViewModel\ViewModel\ContactDetails;
use Hyva\Theme\Model\ViewModelRegistry;
/** @var ViewModelRegistry $viewModels */
/** @var  $contactDetails */
///** @var ContactDetails $contactDetails */

$contactDetails = $viewModels->require(ContactDetails::class);

$heroiconsSolid = $viewModels->require(\Hyva\Theme\ViewModel\HeroiconsSolid::class);

$heroiconsOutline = $viewModels->require(\Hyva\Theme\ViewModel\HeroiconsOutline::class);
?>


<h1>Phone: <?= $contactDetails->getPhoneNumber() ?></h1>
<h2>Product date: <?= $contactDetails->getProduct()->getCreatedAt() ?></h2>


<div><?= $heroiconsSolid->archiveHtml(); ?></div>
<div><?= $heroiconsOutline->archiveHtml(); ?></div>
